### ISSUE TITLE
Include GPU delegate for windows C library

### ISSUE THREAD

**Issue by emepetres** [ValYouW/tflite-dist#1]
Hi, nice work!

I'm wondering if it would be possible to include `tensorflow/lite/delegates/gpu/delegate.h` in the windows C library, so we can run TfLite models on GPU in windows.

Thanks

**Comment by ValYouW** [comment]
Hi, I am not sure it is possible, at least I didn't find a way to build it.
There is a GPU delegate for Android which works pretty good for me...

**Comment by emepetres** [comment]
Yes, but I'm trying to run tflite + gpu on windows, that's why the android library wouldn't work for me...

Thanks anyway :)

**Comment by nische** [comment]
Hi @emepetres,
Did you get TF Lite Working with GPU on Windows??

**Comment by emepetres** [comment]
@nische I tried for a little but didn't seem feasible without entering the rabbit hole :)

**Comment by nische** [comment]
Thanks for your reply. 
Same on my side 😂 I started to use the c api but tf lite would be nicer 🤷🏻‍♂️
