### ISSUE TITLE
.dll .lib library built with arm64 for windows.

### ISSUE THREAD

**Issue by dwdw-song** [ValYouW/tflite-dist#11]
Dear ValYouW
Thank you for letting me know how to build tensorflowlite and sharing dist files from your github.

But, I have a question.
I want to get .dll and .lib files for windows built with arm64 because I'd like to make application used tensorflowlite on windows laptop that it has QC chip.

Could you let me know how to build .dll, .lib with arm64?
please guide to me.

Many thanks.

* I already built x64 with this command (bazel build --config=v2 --config=windows //tensorflow/lite/c:tensorflowlite_c.dll -c opt)

**Comment by ValYouW** [comment]
Hi,
I don't think this is supported by TF:
https://github.com/tensorflow/tensorflow/issues/45151
