### ISSUE TITLE
this just can used for x64, could you compile a win32 dll and lib file?

### ISSUE THREAD

**Issue by djiayong5** [ValYouW/tflite-dist#12]
this just can used for x64, could you compile a win32 dll and lib file?

**Comment by ValYouW** [comment]
As far as I know 32 bit is not supported

**Comment by Yamilemon** [comment]
I think it can be supported: https://github.com/tensorflow/tensorflow/pull/49171

**Comment by ValYouW** [comment]
I'm using Bazel not cmake to build tflite
