### ISSUE TITLE
Node number 0 (FlexPad) failed to prepare

### ISSUE THREAD

**Issue by Amadeus-AI** [ValYouW/tflite-dist#13]
Hi,
Thanks for the great work.
I encountered the following error on win10:
ERROR : Regular TensorFlow ops are not supported by this interpreter.
Make sure you apply / link the Flex delegate before inference.
ERROR : Node number 0 (FlexPad) failed to prepare.

How can I fix it?

**Comment by ValYouW** [comment]
I guess that tflite support only a set of ops by default, and these "Flex" ops are not supported. I am not sure I know how to build with the "flex delegate" support.

**Comment by Amadeus-AI** [comment]
Thanks for the reply:)
