### ISSUE TITLE
How can I use this for a custom yolov4?

### ISSUE THREAD

**Issue by ankits16** [ValYouW/tflite-dist#14]
Thanks a lot for your effort.  Can you please suggest changes if I have to use a custom yolov4 weight here? I have already converted my  darknet trained yolov4 weights to a tflite quantized format

**Comment by ValYouW** [comment]
This library is just the binaries of tflite... if you want to see an example of running tflite you can check out this repo: https://github.com/ValYouW/tflite-win-c
There are multiple models I run there, unfortunately not yolo though...
