### ISSUE TITLE
What is `.dll.if.lib`?

### ISSUE THREAD

**Issue by fzyzcjy** [ValYouW/tflite-dist#15]
Hi thanks for the prebuilt library! I am new to windows programming, so I am a bit confused what is the extension `.dll.if.lib`? I have only seen `.dll` and `.lib` files.

**Comment by ValYouW** [comment]
It's just a regular lib file, you need it in order to link the project with tflite.... not sure why they give it such an extension and not just ".lib"

**Comment by fzyzcjy** [comment]
Interesting... I know what is `lib` and why I need that, just curious whether `.dll.if` prefix has some special meaning. Thank you!
