### ISSUE TITLE
Using windows library with Visual Studio 2022

### ISSUE THREAD

**Issue by raziel2k** [ValYouW/tflite-dist#16]
Hello,
I was using your build of tflite in a VS2019 project. Now I'm moving to VS2022 but, apparently, there are some conflicts (I believe with the VS runtime) becasuse the other projects are no longer able to load my dll. Do you have any clue? Did you use MSYS and Visual Studio 2019 runtime to compile the library?
Best regards

**Comment by ValYouW** [comment]
Hi, the tflite DLLs where built in windows command prompt using Bazel (no msys)

**Comment by raziel2k** [comment]
So you used the Microsoft compiler (MSVC), the one included with Visual Studio 2019, right? I'm wondering if compiling with MSVC Visual Studio 2022 solve my problem.

**Comment by ValYouW** [comment]
I don't remember on which PC I ran the build... but you can try to use "depends" on the dll and see what's inside
