### ISSUE TITLE
Can we use xnnpack in android use  libtensorflowlite.so ？

### ISSUE THREAD

**Issue by moyans** [ValYouW/tflite-dist#17]

**Comment by ValYouW** [comment]
I don't know, I did run it on Windows but never tested Android... If you try please share.

**Comment by moyans** [comment]
I used the C library and didn't find the interface of xnnpack. I found that the xnnpack backend needs to add `--define tflite_with_xnnpack=true` during bazel build

**Comment by ValYouW** [comment]
See this video of mine, the flag is not really necessary, only use the xnnpack delegate:

https://youtu.be/vWbtLIwMrRE

**Comment by moyans** [comment]
Thanks, I successfully used xnnpack on Android and increased the speed by 20+%
