### ISSUE TITLE
.dll .lib library built with x86  for windows

### ISSUE THREAD

**Issue by zuowanbushiwo** [ValYouW/tflite-dist#18]
Dear ValYouW
Thank you for letting me know how to build tensorflowlite and sharing dist files from your github.
I used  your  distribution zip  [v2.7.0](https://github.com/ValYouW/tflite-dist/releases/tag/v2.7.0), but  it can not be used in x86   x86 programs， According to your method,   can compile x86 tflite dll ？

**Comment by ValYouW** [comment]
I dont think it is supported to build 32 bit on windows

**Comment by zuowanbushiwo** [comment]
thanks！
