### ISSUE TITLE
Windows build unresolved externals

### ISSUE THREAD

**Issue by OmarJay1** [ValYouW/tflite-dist#2]
Hello, thanks for putting this together.  I'm finding that that prebuilt packages won't link on Windows.  I built my own with the latest TF pull from github, and the .lib will link properly, but there are other problems with that build.

I get these errors:
1>tflite1.obj : error LNK2019: unresolved external symbol "class tflite::ErrorReporter * __cdecl tflite::DefaultErrorReporter(void)" (?DefaultErrorReporter@tflite@@YAPEAVErrorReporter@1@XZ) referenced in function main
1>tflite1.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class tflite::FlatBufferModel,struct std::default_delete<class tflite::FlatBufferModel> > __cdecl tflite::FlatBufferModel::BuildFromFile(char const *,class tflite::ErrorReporter *)" (?BuildFromFile@FlatBufferModel@tflite@@SA?AV?$unique_ptr@VFlatBufferModel@tflite@@U?$default_delete@VFlatBufferModel@tflite@@@std@@@std@@PEBDPEAVErrorReporter@2@@Z) referenced in function main
1>tflite1.obj : error LNK2019: unresolved external symbol "public: __cdecl tflite::FlatBufferModel::~FlatBufferModel(void)" (??1FlatBufferModel@tflite@@QEAA@XZ) referenced in function "public: void * __cdecl tflite::FlatBufferModel::`scalar deleting destructor'(unsigned int)" (??_GFlatBufferModel@tflite@@QEAAPEAXI@Z)

```
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"

int main(int argc, char* argv[]) 
{
	std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromFile("mobilenet_v1_1.0_224.tflite");

}
```

Thanks.

**Comment by emepetres** [comment]
Hi, you are using the C++ API, but the dll contain only the C API.

In other words, you can only use what it is defined at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/c. Specially look at c_api.h and common.h files.

**Comment by OmarJay1** [comment]
Thanks emepetres.  I don't want to be a pest about this, but I don't believe there's a supported C++ API anymore.  Only TF Lite & C API as far as I can tell, but I could be wrong.

The only implementation of TF Lite I can get to work on Windows is this:

https://github.com/qintao97/tensorflow_lite

If it suits my needs, I'll probably use it.  However, it would be nice to have updates.  I'll look into what it takes to make TF Lite work on Windows.  The Bazel builds seem to be problematic.  The above uses a Visual Studio SLN.

**Comment by ValYouW** [comment]
I think I had tflite c++ working on windows, or was it c?? I'll check soon and update.
Anyway I don't include c++ dll for windows in this distribution as it is huge

**Comment by OmarJay1** [comment]
I guess I was talking about a semantic issue.  I think there used to be a TF C++ API, but it's no longer there.  

The use of .cc files suggests that TF Lite is linked as C++?  I'm not sure, but on Windows my calling code is .cpp.  I was able to build with the latest Bazel .lib.  However, not the .lib in this repository.  

The latest Bazel build fails at runtime when I try something like:

const std::vector<int> inputs = interpreter->inputs();

The lib I pointed to works for getting inputs and analyzing graphs.  I'm going to try to do some inference soon.

Thanks.

**Comment by ValYouW** [comment]
As @emepetres said above, the dll/lib in this repo is of the C library, you can't compile your code using tflite c++ headers (eg `tensorflow/lite/model.h`) and link against the C lib provided here. If you want to use the lib provided here you have to use tflite C headers (i.e `tensorflow/lite/c/c_api.h`), it does not matter if you write in c++, in [this](https://github.com/ValYouW/tflite-win-c) sample I write in C++ but using the C headers of tflite.
Do you have to use the c++ headers?
