### ISSUE TITLE
where TFlite_2.3.0

### ISSUE THREAD

**Issue by Tomhouxin** [ValYouW/tflite-dist#4]
where TFlite_2.3.0 of Release

**Comment by ValYouW** [comment]
This is not an automated process, I have to build these manually and I dont do this for every version, I try to do it only for "official" releases. As I see 2.3.0 is not out yet (it is rc-2)

**Comment by Tomhouxin** [comment]
how to bazel build tflite2.3 on mac,thanks

**Comment by ValYouW** [comment]
To build for iOS try [this](https://www.tensorflow.org/lite/guide/build_ios).
As for 2.3.0 I made a release few weeks ago...

**Comment by Tomhouxin** [comment]
Yes, I want to build tflite2 on mac too, I can not open [this](https://www.tensorflow.org/lite/guide/build_ios)
