### ISSUE TITLE
Tflite model 

### ISSUE THREAD

**Issue by YousIA** [ValYouW/tflite-dist#5]
Dear Yuval, 
Thank you for this interesting code. Please could you provide me the tflite model used.? 
Best Regards,

**Comment by ValYouW** [comment]
What do you mean? There's no model here... Maybe you are confusing with another repository?

**Comment by YousIA** [comment]
I am so sorry. I mean the tflite model used in this video: https://www.youtube.com/watch?v=dox1ZkFP-f4

**Comment by ValYouW** [comment]
Oh, check that project repo:
https://github.com/ValYouW/tflite-win-c

**Comment by YousIA** [comment]
Thank you so much!
