### ISSUE TITLE
Windows x86 library

### ISSUE THREAD

**Issue by rribani** [ValYouW/tflite-dist#6]
Hi @ValYouW,

Nice job on this work!

I'm trying to build TFLite for Windows to support x86, ARM, and ARM64. Do you know if this is possible? 

When I set --cpu=x86, I see this error:

INFO: Build option --cpu has changed, discarding analysis cache.
ERROR: C:/users/ribani/_bazel_ribani/s3scxrxn/external/cpuinfo/BUILD.bazel:96:11: Configurable attribute "srcs" doesn't match this configuration (would a default condition help?).
Conditions checked:
 @cpuinfo//:linux_x86_64 
 @cpuinfo//:linux_arm   
 @cpuinfo//:linux_armhf  
 @cpuinfo//:linux_armv7a  
 @cpuinfo//:linux_armeabi  
 @cpuinfo//:linux_aarch64  
 @cpuinfo//:macos_x86_64  
 @cpuinfo//:windows_x86_64  
 @cpuinfo//:android_armv7  
 @cpuinfo//:android_arm64  
 @cpuinfo//:android_x86  
 @cpuinfo//:android_x86_64  
 @cpuinfo//:ios_x86_64  
 @cpuinfo//:ios_x86  
 @cpuinfo//:ios_armv7  
 @cpuinfo//:ios_arm64  
 @cpuinfo//:ios_arm64e  
 @cpuinfo//:watchos_x86_64  
 @cpuinfo//:watchos_x86  
 @cpuinfo//:watchos_armv7k  
 @cpuinfo//:watchos_arm64_32  
 @cpuinfo//:tvos_x86_64  
 @cpuinfo//:tvos_arm64  
ERROR: Analysis of target '//tensorflow/lite/c:tensorflowlite_c.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 31.720s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 1171 targets configured)

Thanks.

**Comment by ValYouW** [comment]
I am not sure tflite can be built for 32bit arch. When I build for windows I use this command:
```
bazel build //tensorflow/lite/c:tensorflowlite_c.dll -c opt --config=windows
```
You should open issue with tensorflow to figure it out, and if you do would appreciate an update!
