### ISSUE TITLE
Not found x86 for windows

### ISSUE THREAD

**Issue by DyncEric** [ValYouW/tflite-dist#7]
Not found x86 for win32 in tflite-dist.zip, just found one x64 library.

**Comment by ValYouW** [comment]
Not supported by TF

**Comment by DyncEric** [comment]
Thanks

**Comment by leospark** [comment]
> Not supported by TF



> Not supported by TF
Here are some good tests: 
https://github.com/tensorflow/tensorflow/issues/47166
