### ISSUE TITLE
Not found libtensorflowlite.so for linux

### ISSUE THREAD

**Issue by aishoot** [ValYouW/tflite-dist#9]
Hello, thanks for your sharing. But I didn't find the libtensorflowlite.so for linux and how can I use your [bash script](https://github.com/ValYouW/tflite-dist/blob/master/build-android.sh) to generate it? Thanks!

**Comment by ValYouW** [comment]
I don't build for linux, not sure how to be honest, maybe you can try these instructions:
https://www.tensorflow.org/lite/guide/build_arm64

**Comment by aishoot** [comment]
@ValYouW Thanks, I have built it fot linux.

**Comment by ValYouW** [comment]
Great
